[arbitrum]
rpc_url = "${ARBITRUM_RPC_URL}"

[arbitrum.address]
deployer = "${ETH_KEYSTORE_ADDRESS}"

# Curve
# https://docs.curve.finance/references/deployed-contracts/#stableswap-ng
curve_stableswap_ng_factory_address = "0x9AF14D26075f142eb3F292D5065EB3faa646167b"

# https://developers.circle.com/stablecoins/usdc-contract-addresses
# usdc_address = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"

[arbitrum.string]
network_name = "arbitrum"

# ApxUSD
apx_usd_name = "Foo USD"
apx_usd_symbol = "fooUSD"

apx_usd_supply_cap = "1_000_000_000"
apx_usd_max_mint_size = "1_000_000"

apx_usd_rate_limit_mint_size = "10_000_000"
apx_usd_rate_limit_mint_period = "86400"    # seconds

# ApyUSD
apy_usd_name = "Bar USD"
apy_usd_symbol = "barUSD"

apx_usd_mint_delay = "5"       # seconds
apy_usd_unlocking_delay = "60" # seconds

# CommitToken
commit_token_default_supply_cap = "10000000" # 10M
commit_token_default_unlocking_delay = "60"  # seconds

# Vesting
vesting_period = "86400" # 1 day in seconds

# Curve ApxUSD Pool
curve_pool_apx_usd_usdc_name = "Curve.fi fooUSD-mockUSDC"
curve_pool_apx_usd_usdc_symbol = "fooUSDmock"                 # max 10 chars
curve_pool_apx_usd_usdc_amplification = "400"
curve_pool_apx_usd_usdc_fee = "4000000"
curve_pool_apx_usd_usdc_offpeg_fee_multiplier = "20000000000"
curve_pool_apx_usd_usdc_ma_exp_time = "866"
curve_pool_apx_usd_usdc_implementation_idx = "0"
