[arbitrum]
rpc_url = "${ARBITRUM_RPC_URL}"

[arbitrum.address]
deployer = "${ARBITRUM_DEPLOYER}"
authority = "${ARBITRUM_AUTHORITY}"

# Curve
# https://docs.curve.finance/references/deployed-contracts/#stableswap-ng
curve_stableswap_ng_factory_address = "0x9AF14D26075f142eb3F292D5065EB3faa646167b"
# https://docs.curve.finance/references/deployed-contracts/#twocrypto-ng
curve_twocrypto_ng_factory_address = "0x98EE851a00abeE0d95D08cF4CA2BdCE32aeaAF7F"

# https://developers.circle.com/stablecoins/usdc-contract-addresses
# usdc_address = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"

[arbitrum.string]
network_name = "arbitrum"

# ApxUSD
apx_usd_name = "Foo USD"
apx_usd_symbol = "fooUSD"

apx_usd_supply_cap = "1_000_000_000"
apx_usd_max_mint_size = "1_000_000"

apx_usd_rate_limit_mint_size = "10_000_000"
apx_usd_rate_limit_mint_period = "86400"    # seconds

# ApyUSD
apy_usd_name = "Bar USD"
apy_usd_symbol = "barUSD"

apx_usd_mint_delay = "5"       # seconds
apy_usd_unlocking_delay = "60" # seconds

# CommitToken
commit_token_default_supply_cap = "10000000" # 10M ether (1e18)
commit_token_default_unlocking_delay = "60"  # seconds

# Vesting
vesting_period = "2592000" # 30 days in seconds

# Curve ApxUSD Pool (Stableswap-NG)
curve_pool_apx_usd_usdc_name = "Curve.fi fooUSD-mockUSDC"
curve_pool_apx_usd_usdc_symbol = "fooUSDmock"                 # max 10 chars
curve_pool_apx_usd_usdc_amplification = "400"
curve_pool_apx_usd_usdc_fee = "4000000"
curve_pool_apx_usd_usdc_offpeg_fee_multiplier = "20000000000"
curve_pool_apx_usd_usdc_ma_exp_time = "866"
curve_pool_apx_usd_usdc_implementation_idx = "0"

# Curve ApyUSD-MockUSD Pool (Twocrypto-NG)
# https://docs.curve.finance/cryptoswap-exchange/in-depth/
curve_pool_apy_usd_mock_usd_name = "Curve.fi barUSD-mockUSD"
curve_pool_apy_usd_mock_usd_symbol = "barUSDmock"                 # max 10 chars
curve_pool_apy_usd_mock_usd_implementation_id = "0"
curve_pool_apy_usd_mock_usd_A = "20000000"
curve_pool_apy_usd_mock_usd_gamma = "10000000000000000"
curve_pool_apy_usd_mock_usd_mid_fee = "3000000"
curve_pool_apy_usd_mock_usd_out_fee = "45000000"
curve_pool_apy_usd_mock_usd_fee_gamma = "300000000000000000"
curve_pool_apy_usd_mock_usd_allowed_extra_profit = "10000000000"
curve_pool_apy_usd_mock_usd_adjustment_step = "5500000000000"
curve_pool_apy_usd_mock_usd_ma_exp_time = "600"
curve_pool_apy_usd_mock_usd_initial_price = "1000000000000000000"

[mainnet]
rpc_url = "${ETHEREUM_RPC_URL}"

[mainnet.address]
deployer = "${ETHEREUM_DEPLOYER}"
authority = "${ETHEREUM_AUTHORITY}"

[mainnet.string]
network_name = "mainnet"

# ApxUSD
apx_usd_name = "apxUSD"
apx_usd_symbol = "apxUSD"

# ApyUSD
apy_usd_unlocking_delay = "2592000" # 30 days in seconds

# Commit Token
commit_token_default_unlocking_delay = "1209600" # 14 days in seconds

commit_token_supply_cap_apx_usd = "100_000_000"
commit_token_supply_cap_curve_apx_usd_usdc = "50_000_000"
commit_token_supply_cap_curve_apy_usd_usdc = "20_000_000"
commit_token_supply_cap_curve_apx_apy_usd = "20_000_000"

[mainnet.uint]
# ApxUSD
apx_usd_supply_cap = 100_000_000e18 # $100M

# Minting 
apx_usd_mint_delay = 14400                   # 4 hours in seconds
apx_usd_max_mint_size = 10_000_000e18        # $10M
apx_usd_rate_limit_mint_size = 10_000_000e18 # $10M
apx_usd_rate_limit_mint_period = 86400       # 24 hours in seconds
