[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

fs_permissions = [
    { access = "read-write", path = "./config.toml" },
    { access = "read-write", path = "./out" },
    { access = "read-write", path = "./deploy" },
    { access = "read-write", path = "./reports" },
]

[invariant]
runs = 32
depth = 32
fail_on_revert = true

[profile.release]
solc_version = "0.8.30"
# Use the IR compiler and optimizer
via_ir = true
optimizer = true
# Skip compiling test files
test = "skip"
# Fail if any warnings are present
deny = "warnings"

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"

[lint]
exclude_lints = [
    "mixed-case-variable",
    "mixed-case-function",
    "pascal-case-struct",
]

[dependencies]
forge-std = "1.11.0"
"@openzeppelin-contracts-upgradeable" = "5.5.0"
"@openzeppelin-contracts" = "5.5.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
