apiVersion: v1
kind: Config
preferences: {}

current-context: dev-admin

contexts:
- name: dev-admin
  context:
    cluster: dev
    user: dev-admin
- name: dev-fragmetric
  context:
    cluster: dev
    user: dev-fragmetric

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQzZjeDhKcmhPbWN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1UY3dNekE0TUROYUZ3MHpOVEV5TVRVd016RXpNRE5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMrQ2dLYnptbEhHYXRHcTJhTFB2RFNsODFvMEpHd0RJbXc0ZjNkcUxSNnRyeVhWbytmbzM3amkvTm0KT0U3YWJUYUJRRjBOYkNFUVNXM0ZNTUJKSFpBbkNjdG1Oa3JtRzMvMS9xS0hTaEdDejB4clRqYmtKVVdScUJrNAo2TDVqYklkbWlCWHZDa3JKQVovcUVQa2RhdjdwcWgwZnU3YjdxWEkyQkFEUXp1TVEzMXhnNFUvVktsSnBDOHZ6CjY3UnIvdjh0UEZpSlFFTmdaU1NyQmxHaU8vRUNUR2FmQ3FpS3ZuTDV5TGRzWWxTRUFYRzBEWmx5QjYxQ21rYk4KdkhPSGxsd09pVWFYQnE4d2ZISFdiZUVKQzFTVmVERnpQL1RoNnN0aVIzM09wMXZQdXVWMHFIeStqNDFoV3NmZQpxUjU4cUM4dUViUyt5VFFVWWpoVHZPaDV0RjVwQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUM0lOMmZPbDFSajZTYUljUDhsQjNtNGRWVmZ6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmhtNlBWWUpDNQppMkZ2TlZlaGpjb3pKck5PQ2krM2RROGUvSmNXV3QxVU0vb2g1elh5VXp4VW1iNTdoZkt1ejg4Y0FnSFg3UEwzClRNaWl5VlRXeGFzYW1mbXNCQWdMaElNSzJDeHpqWjliaGdteHY5dm13MDBtMVNicit4S3p4VHFtOGlaS0FhcVIKRHFxVmliVkVJL1Y3OGdaMlRTQUE2cmhpa2xhTHdXTmZUazQ1SVV3b05tSkpjVTg5cjZvTVdLbzR4MUczSUU3ZQpJWmV0dTVFOUxGdWlRMWdya3BDaXRRQ3JiYzNzTUJ3TTVMWlJyVy9LQ1lNbFJOdlk5cGM2YmZsaUJCdDRZSFZTClQwU3FDMWE4WHQxMmEvTzAyZjlPdmY0ZUVzRFRNNWxDRENkeVQ2TWNWWllaekF4WWQvdU1YSTNvdWF6a2RxTjkKQjhEV0JGZ1pXUFRZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0B00D161441D372E4ABEEB62A1BF3EFA.gr7.ap-southeast-1.eks.amazonaws.com
  name: dev
  
users:
- name: dev-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-southeast-1
      - eks
      - get-token
      - --cluster-name
      - dev
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: dev-admin

- name: dev-fragmetric
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-southeast-1
      - eks
      - get-token
      - --cluster-name
      - dev
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: dev-fragmetric
